services:
  app:
    build:
      context: .
      dockerfile: compose/frankenphp/Dockerfile
    container_name: horizon-app
    volumes:
      - ./src:/app
      - ./src/vendor:/app/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - SERVER_NAME=:80
      - DB_CONNECTION=sqlite
#      - DB_HOST=db
#      - DB_PORT=3306
#      - DB_DATABASE=horizon_app
#      - DB_USERNAME=laravel
#      - DB_PASSWORD=secret
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  redis:
    container_name: horizon-redis
    image: 'redis:alpine'
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

#  db:
#    image: mysql:8.0
#    container_name: frankenphp-laravel-db
#    environment:
#      MYSQL_DATABASE: laravel
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_PASSWORD: secret
#      MYSQL_USER: laravel
#      SERVICE_TAGS: dev
#      SERVICE_NAME: mysql
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - laravel-network
#    ports:
#      - "3306:3306"


networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
